project_id = "fbhhumtpdfalgkhzirew"

[functions.ai-chat]
verify_jwt = false

[functions."chat-find-or-create-dm"]
verify_jwt = true

[functions.ai-targeting]
verify_jwt = false

[functions.fetch-link-metadata]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false
